name: delivery
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.1
  cached_network_image: ^3.1.0+1
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter_bloc: ^7.3.0
  flutter_blurhash: ^0.6.0
  flutter_lorem: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.23.0
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  go_router: ^2.3.1
  google_fonts: ^2.1.0
  grpc: ^3.0.2
  injectable: ^1.4.1
  octo_image: ^1.0.0+1
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter test integration_test/app_test.dart
  integration_test:
    sdk: flutter

  bloc_test: ^8.0.2
  build_runner: ^2.1.1
  flutter_lints: ^1.0.3
  freezed: ^0.14.2
  import_sorter: ^4.6.0
  injectable_generator: ^1.4.1
  # generate the mocks running the following command:
  # flutter pub run build_runner build
  # flutter pub run build_runner build --delete-conflicting-outputs
  mockito: ^5.0.10

import_sorter:
  emojis: true
  comments: true
  ignored_files:
    - \/lib\/protos
    # - \/**\/*.mocks.dart
    # - \/**\/*.config.dart

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
