// Mocks generated by Mockito 5.0.15 from annotations
// in delivery/test/feature/data/repositories/delvery_repository_impl_test.dart.
// Do not manually edit this file.

// 🎯 Dart imports:
import 'dart:async' as _i4;

// 📦 Package imports:
import 'package:mockito/mockito.dart' as _i1;

// 🌎 Project imports:
import 'package:delivery/protos/protos/main.pbgrpc.dart' as _i2;

import 'package:delivery/feature/data/datasource/delivery_data_source.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeItem_0 extends _i1.Fake implements _i2.Item {}

/// A class which mocks [DeliveryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryDataSource extends _i1.Mock
    implements _i3.DeliveryDataSource {
  MockDeliveryDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Item>> getItems() =>
      (super.noSuchMethod(Invocation.method(#getItems, []),
              returnValue: Future<List<_i2.Item>>.value(<_i2.Item>[]))
          as _i4.Future<List<_i2.Item>>);
  @override
  _i4.Future<_i2.Item> getItemDetails(String? id) =>
      (super.noSuchMethod(Invocation.method(#getItemDetails, [id]),
              returnValue: Future<_i2.Item>.value(_FakeItem_0()))
          as _i4.Future<_i2.Item>);
  @override
  String toString() => super.toString();
}
